"""leads types

Revision ID: 104ba4c98a87
Revises: 938b2a408791
Create Date: 2025-03-12 03:38:31.250873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '104ba4c98a87'
down_revision: Union[str, None] = '938b2a408791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads_types',
    sa.Column('company_domain', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_type', sa.String(length=50), nullable=True),
    sa.Column('date_added', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_domain'], ['company_info.company_domain'], ),
    sa.PrimaryKeyConstraint('company_domain', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads_types')
    # ### end Alembic commands ###
