"""client

Revision ID: 3f64be4d7d6c
Revises: d1ee3055db0e
Create Date: 2025-03-12 05:48:37.928005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f64be4d7d6c'
down_revision: Union[str, None] = 'd1ee3055db0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_meetings',
    sa.Column('meeting_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_added', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('company_domain', sa.String(length=100), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('meeting_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('meeting_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['user_info.id'], ),
    sa.ForeignKeyConstraint(['company_domain', 'meeting_status'], ['meetings_status.company_domain', 'meetings_status.id'], ),
    sa.ForeignKeyConstraint(['company_domain'], ['company_info.company_domain'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads_info.lead_id'], ),
    sa.PrimaryKeyConstraint('meeting_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_meetings')
    # ### end Alembic commands ###
