"""add salary model

Revision ID: 52f7b52fe9aa
Revises: c938204e994b
Create Date: 2025-03-13 06:01:05.707833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f7b52fe9aa'
down_revision: Union[str, None] = 'c938204e994b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees_salaries',
    sa.Column('company_domain', sa.String(length=100), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('gross_salary', sa.Numeric(), nullable=True),
    sa.Column('insurance', sa.Numeric(), nullable=True),
    sa.Column('taxes', sa.Numeric(), nullable=True),
    sa.Column('net_salary', sa.Numeric(), nullable=True),
    sa.Column('due_year', sa.Integer(), nullable=False),
    sa.Column('due_month', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_domain', 'employee_id'], ['employees_info.company_domain', 'employees_info.employee_id'], ),
    sa.PrimaryKeyConstraint('company_domain', 'employee_id', 'due_year', 'due_month')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees_salaries')
    # ### end Alembic commands ###
