"""client calls

Revision ID: a6ead215b93f
Revises: 3f64be4d7d6c
Create Date: 2025-03-12 05:50:10.981554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ead215b93f'
down_revision: Union[str, None] = '3f64be4d7d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_calls',
    sa.Column('call_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_added', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('company_domain', sa.String(length=100), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('call_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('call_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['user_info.id'], ),
    sa.ForeignKeyConstraint(['company_domain', 'call_status'], ['calls_status.company_domain', 'calls_status.id'], ),
    sa.ForeignKeyConstraint(['company_domain'], ['company_info.company_domain'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads_info.lead_id'], ),
    sa.PrimaryKeyConstraint('call_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_calls')
    # ### end Alembic commands ###
