"""add employee model

Revision ID: c938204e994b
Revises: f00e44ee8f67
Create Date: 2025-03-13 05:59:37.835417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c938204e994b'
down_revision: Union[str, None] = 'f00e44ee8f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees_info',
    sa.Column('date_added', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('company_domain', sa.String(length=100), nullable=False),
    sa.Column('employee_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_name', sa.String(length=50), nullable=False),
    sa.Column('business_phone', sa.String(length=50), nullable=True),
    sa.Column('personal_phone', sa.String(length=50), nullable=True),
    sa.Column('business_email', sa.String(length=50), nullable=True),
    sa.Column('personal_email', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('is_company_admin', sa.Boolean(), nullable=True),
    sa.Column('user_uid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_domain'], ['company_info.company_domain'], ),
    sa.PrimaryKeyConstraint('company_domain', 'employee_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees_info')
    # ### end Alembic commands ###
