"""leads info

Revision ID: d1ee3055db0e
Revises: ac87a225c380
Create Date: 2025-03-12 05:46:16.886977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1ee3055db0e'
down_revision: Union[str, None] = 'ac87a225c380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads_info',
    sa.Column('date_added', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('lead_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_domain', sa.String(length=100), nullable=False),
    sa.Column('lead_phone', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('lead_stage', sa.Integer(), nullable=True),
    sa.Column('lead_type', sa.Integer(), nullable=True),
    sa.Column('lead_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['user_info.id'], ),
    sa.ForeignKeyConstraint(['company_domain', 'lead_stage'], ['leads_stage.company_domain', 'leads_stage.id'], ),
    sa.ForeignKeyConstraint(['company_domain', 'lead_status'], ['leads_status.company_domain', 'leads_status.id'], ),
    sa.ForeignKeyConstraint(['company_domain', 'lead_type'], ['leads_types.company_domain', 'leads_types.id'], ),
    sa.PrimaryKeyConstraint('lead_id'),
    sa.UniqueConstraint('lead_phone')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads_info')
    # ### end Alembic commands ###
